// <auto-generated />
using System;
using AppVinhosFinal.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppVinhosFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250726160149_f0")]
    partial class f0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppVinhosFinal.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuintaId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("QuintaId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "291c2f92-03cc-4503-b5d1-8b218398e7fb",
                            CreatedAt = new DateTime(2025, 7, 11, 7, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = false,
                            NormalizedEmail = "ADMIN@VINHOS.PT",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEO8iofkkhWRBNQcPkXccBXQ65huiErAJJcgVebPwaZZXGjDR5j4mtmfnGB0lgOOjQg==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "b8c88586-0b9e-417d-a197-5639d5565133",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "29171b24-b5c3-4ad8-ae64-3734b05061bc",
                            CreatedAt = new DateTime(2025, 7, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff01@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = false,
                            NormalizedEmail = "STAFF01@VINHOS.PT",
                            NormalizedUserName = "STAFF01",
                            PasswordHash = "AQAAAAIAAYagAAAAEIOHA5A0gYXxuOqORW1iT6maou2mVvZOJHWbMo/SBc4YFl7I6pBuu8CruYX/y+Iw/g==",
                            PhoneNumberConfirmed = false,
                            Role = "Staff",
                            SecurityStamp = "31e0de36-b637-4349-862f-a4728b6a7e8b",
                            TwoFactorEnabled = false,
                            UserName = "staff01"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b500abf-b4c8-45ea-a36f-ba3fc4e9ad07",
                            CreatedAt = new DateTime(2025, 7, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "visit1@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = true,
                            NormalizedEmail = "VISIT1@VINHOS.PT",
                            NormalizedUserName = "VISITANTE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEFhp7WjlPuxISOnedWYfiIFMfrESfSbBmxJhd3PUrvz+9E2B/0Isle6cdb9f7ZM8Ow==",
                            PhoneNumberConfirmed = false,
                            QuintaId = 2,
                            Role = "User",
                            SecurityStamp = "7a503764-15e5-43c4-8b9f-9413d99fb7c9",
                            TwoFactorEnabled = false,
                            UserName = "visitante1"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00efb5f8-206f-4562-b25f-89c8009495ac",
                            CreatedAt = new DateTime(2025, 7, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            Email = "user01@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = false,
                            NormalizedEmail = "USER01@VINHOS.PT",
                            NormalizedUserName = "USER01",
                            PasswordHash = "AQAAAAIAAYagAAAAEFhwfFR2V9+2lldE4Wm1YoTwgGMR7T5EOgU6dTa8JkXu8eUZVIo87LsoMgpQTTcIXg==",
                            PhoneNumberConfirmed = false,
                            QuintaId = 1,
                            Role = "User",
                            SecurityStamp = "98312e59-9e9f-4208-b537-5e6f6d060dd6",
                            TwoFactorEnabled = false,
                            UserName = "user01"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "32dae27b-e17c-458f-8c23-e7c84e833566",
                            CreatedAt = new DateTime(2025, 7, 10, 16, 45, 0, 0, DateTimeKind.Utc),
                            Email = "convid@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = false,
                            NormalizedEmail = "CONVID@VINHOS.PT",
                            NormalizedUserName = "CONVIDADO",
                            PasswordHash = "AQAAAAIAAYagAAAAEOgSsyWLFtq1/ZaiRX9Uds5To6jMaZk80jZ7zzFa+jmOJ9ZQvtoAUIycoFD5Yv/Rhg==",
                            PhoneNumberConfirmed = false,
                            QuintaId = 5,
                            Role = "User",
                            SecurityStamp = "dc3c0e0e-c0ed-4765-88a1-68fdf6089c3b",
                            TwoFactorEnabled = false,
                            UserName = "convidado"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc97975f-4437-4363-b53d-9877d58d9a8d",
                            CreatedAt = new DateTime(2025, 7, 9, 12, 20, 0, 0, DateTimeKind.Utc),
                            Email = "guest2@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = true,
                            NormalizedEmail = "GUEST2@VINHOS.PT",
                            NormalizedUserName = "GUEST2",
                            PasswordHash = "AQAAAAIAAYagAAAAEHusYjgay17N1b4Y4qeZILOnBhZ04W48epLU9xso4G7LlQsd3awvpAIQfve8P3z96g==",
                            PhoneNumberConfirmed = false,
                            QuintaId = 6,
                            Role = "User",
                            SecurityStamp = "6057d2dd-ab9a-44a4-9819-a84bfbfc7808",
                            TwoFactorEnabled = false,
                            UserName = "guest2"
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.LogsCopos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprador")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHoraVenda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("QuantidadeVendida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LogsCopos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comprador = "Cliente X",
                            DataHoraVenda = new DateTime(2025, 7, 11, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 12
                        },
                        new
                        {
                            Id = 2,
                            DataHoraVenda = new DateTime(2025, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 8
                        },
                        new
                        {
                            Id = 3,
                            Comprador = "Cliente Y",
                            DataHoraVenda = new DateTime(2025, 7, 10, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 25
                        },
                        new
                        {
                            Id = 4,
                            Comprador = "Cliente Z",
                            DataHoraVenda = new DateTime(2025, 7, 9, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 5
                        },
                        new
                        {
                            Id = 5,
                            Comprador = "Cliente W",
                            DataHoraVenda = new DateTime(2025, 7, 9, 19, 20, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 18
                        },
                        new
                        {
                            Id = 6,
                            Comprador = "Sem Venda",
                            DataHoraVenda = new DateTime(2025, 7, 8, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 0
                        },
                        new
                        {
                            Id = 7,
                            DataHoraVenda = new DateTime(2025, 7, 7, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 50
                        },
                        new
                        {
                            Id = 8,
                            Comprador = "Cliente K",
                            DataHoraVenda = new DateTime(2025, 7, 6, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 7
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QuintaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.PedidoVinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer");

                    b.Property<int>("IdVinho")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdVinho");

                    b.ToTable("PedidoVinhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdPedido = 1,
                            IdVinho = 1,
                            Quantidade = 5,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            IdPedido = 2,
                            IdVinho = 2,
                            Quantidade = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            IdPedido = 2,
                            IdVinho = 4,
                            Quantidade = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 4,
                            IdPedido = 3,
                            IdVinho = 9,
                            Quantidade = 10,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 5,
                            IdPedido = 4,
                            IdVinho = 10,
                            Quantidade = 15,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 6,
                            IdPedido = 4,
                            IdVinho = 12,
                            Quantidade = 5,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 7,
                            IdPedido = 5,
                            IdVinho = 13,
                            Quantidade = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 8,
                            IdPedido = 5,
                            IdVinho = 13,
                            Quantidade = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 9,
                            IdPedido = 6,
                            IdVinho = 17,
                            Quantidade = 5,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 10,
                            IdPedido = 6,
                            IdVinho = 19,
                            Quantidade = 4,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 11,
                            IdPedido = 7,
                            IdVinho = 21,
                            Quantidade = 6,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 12,
                            IdPedido = 8,
                            IdVinho = 22,
                            Quantidade = 8,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 13,
                            IdPedido = 8,
                            IdVinho = 23,
                            Quantidade = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 14,
                            IdPedido = 8,
                            IdVinho = 24,
                            Quantidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 15,
                            IdPedido = 9,
                            IdVinho = 5,
                            Quantidade = 7,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 16,
                            IdPedido = 9,
                            IdVinho = 6,
                            Quantidade = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 17,
                            IdPedido = 9,
                            IdVinho = 7,
                            Quantidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 18,
                            IdPedido = 10,
                            IdVinho = 12,
                            Quantidade = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 19,
                            IdPedido = 11,
                            IdVinho = 3,
                            Quantidade = 10,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 20,
                            IdPedido = 11,
                            IdVinho = 1,
                            Quantidade = 2,
                            Tipo = 0
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Pedidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataPedido = new DateTime(2025, 7, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 2,
                            DataAprovacao = new DateTime(2025, 7, 11, 9, 35, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 3,
                            DataPedido = new DateTime(2025, 7, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            Estado = 2
                        },
                        new
                        {
                            Id = 4,
                            DataAprovacao = new DateTime(2025, 7, 11, 16, 10, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 10, 16, 5, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 5,
                            DataPedido = new DateTime(2025, 7, 10, 18, 20, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 6,
                            DataAprovacao = new DateTime(2025, 7, 10, 10, 17, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 9, 10, 15, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 7,
                            DataPedido = new DateTime(2025, 7, 9, 12, 45, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 8,
                            DataPedido = new DateTime(2025, 7, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Estado = 2
                        },
                        new
                        {
                            Id = 9,
                            DataAprovacao = new DateTime(2025, 7, 9, 16, 35, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 8, 16, 30, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 10,
                            DataPedido = new DateTime(2025, 7, 7, 11, 15, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 11,
                            DataPedido = new DateTime(2025, 7, 7, 13, 25, 0, 0, DateTimeKind.Utc),
                            Estado = 2
                        },
                        new
                        {
                            Id = 12,
                            DataAprovacao = new DateTime(2025, 7, 7, 15, 50, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 6, 15, 45, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Quintas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroMaxVinhoFrio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Quintas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Quinta Modelo",
                            NumeroMaxVinhoFrio = 20
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Quinta Vazia",
                            NumeroMaxVinhoFrio = 0
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Quinta dos Sonhos",
                            NumeroMaxVinhoFrio = 50
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Vinhedo Real",
                            NumeroMaxVinhoFrio = 30
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Encostas do Douro",
                            NumeroMaxVinhoFrio = 40
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Vale do Champagne",
                            NumeroMaxVinhoFrio = 60
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeFria")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("IdQuinta")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeFria")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdQuinta");

                    b.ToTable("Vinhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Tinto Clássico",
                            Quantidade = 50,
                            QuantidadeFria = 10
                        },
                        new
                        {
                            Id = 2,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Branco Seco",
                            Quantidade = 40,
                            QuantidadeFria = 5
                        },
                        new
                        {
                            Id = 3,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Rosé Alegre",
                            Quantidade = 60,
                            QuantidadeFria = 20
                        },
                        new
                        {
                            Id = 4,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Espumante Delicado",
                            Quantidade = 30,
                            QuantidadeFria = 30
                        },
                        new
                        {
                            Id = 5,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 2,
                            Nome = "Tinto Intenso II",
                            Quantidade = 45,
                            QuantidadeFria = 0
                        },
                        new
                        {
                            Id = 6,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 2,
                            Nome = "Branco Floral",
                            Quantidade = 25,
                            QuantidadeFria = 25
                        },
                        new
                        {
                            Id = 7,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 2,
                            Nome = "Rosé de Verão",
                            Quantidade = 70,
                            QuantidadeFria = 35
                        },
                        new
                        {
                            Id = 8,
                            CapacidadeFria = 0,
                            Estado = 1,
                            IdQuinta = 2,
                            Nome = "Espumante Brut",
                            Quantidade = 80,
                            QuantidadeFria = 50
                        },
                        new
                        {
                            Id = 9,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Tinto Reserva",
                            Quantidade = 75,
                            QuantidadeFria = 15
                        },
                        new
                        {
                            Id = 10,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Branco Suave",
                            Quantidade = 90,
                            QuantidadeFria = 45
                        },
                        new
                        {
                            Id = 11,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Rosé Primavera",
                            Quantidade = 100,
                            QuantidadeFria = 60
                        },
                        new
                        {
                            Id = 12,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Espumante Rosé",
                            Quantidade = 50,
                            QuantidadeFria = 50
                        },
                        new
                        {
                            Id = 13,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 4,
                            Nome = "Tinto Envelhecido",
                            Quantidade = 40,
                            QuantidadeFria = 20
                        },
                        new
                        {
                            Id = 14,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 4,
                            Nome = "Branco Cítrico",
                            Quantidade = 60,
                            QuantidadeFria = 30
                        },
                        new
                        {
                            Id = 15,
                            CapacidadeFria = 0,
                            Estado = 1,
                            IdQuinta = 4,
                            Nome = "Rosé Aromático",
                            Quantidade = 55,
                            QuantidadeFria = 25
                        },
                        new
                        {
                            Id = 16,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 4,
                            Nome = "Espumante Premium",
                            Quantidade = 80,
                            QuantidadeFria = 80
                        },
                        new
                        {
                            Id = 17,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Tinto Ensolarado",
                            Quantidade = 65,
                            QuantidadeFria = 35
                        },
                        new
                        {
                            Id = 18,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Branco Seco Especial",
                            Quantidade = 110,
                            QuantidadeFria = 70
                        },
                        new
                        {
                            Id = 19,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Rosé Tropical",
                            Quantidade = 85,
                            QuantidadeFria = 45
                        },
                        new
                        {
                            Id = 20,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Espumante de Honra",
                            Quantidade = 90,
                            QuantidadeFria = 60
                        },
                        new
                        {
                            Id = 21,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Tinto Forte",
                            Quantidade = 80,
                            QuantidadeFria = 40
                        },
                        new
                        {
                            Id = 22,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Branco Frutado",
                            Quantidade = 95,
                            QuantidadeFria = 50
                        },
                        new
                        {
                            Id = 23,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Rosé Encantado",
                            Quantidade = 120,
                            QuantidadeFria = 60
                        },
                        new
                        {
                            Id = 24,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Espumante Real",
                            Quantidade = 100,
                            QuantidadeFria = 80
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppVinhosFinal.Entities.UserAccount", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Quintas", "Quinta")
                        .WithMany("UserAccounts")
                        .HasForeignKey("QuintaId");

                    b.Navigation("Quinta");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.PedidoVinho", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Pedidos", "Pedido")
                        .WithMany("PedidoVinhos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppVinhosFinal.Models.Vinhos", "Vinho")
                        .WithMany("PedidoVinhos")
                        .HasForeignKey("IdVinho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Vinho");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Quintas", "Quinta")
                        .WithMany("Vinhos")
                        .HasForeignKey("IdQuinta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quinta");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AppVinhosFinal.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AppVinhosFinal.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppVinhosFinal.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AppVinhosFinal.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Pedidos", b =>
                {
                    b.Navigation("PedidoVinhos");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Quintas", b =>
                {
                    b.Navigation("UserAccounts");

                    b.Navigation("Vinhos");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.Navigation("PedidoVinhos");
                });
#pragma warning restore 612, 618
        }
    }
}
