// <auto-generated />
using System;
using AppVinhosFinal.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppVinhosFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppVinhosFinal.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuintaId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuintaId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 11, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@vinhos.pt",
                            MustChangePassword = false,
                            Password = "Admin123!",
                            QuintaId = 1,
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff01@vinhos.pt",
                            MustChangePassword = false,
                            Password = "Staff123!",
                            QuintaId = 3,
                            Role = "Staff",
                            UserName = "staff01"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "visit1@vinhos.pt",
                            MustChangePassword = true,
                            Password = "Guest123!",
                            QuintaId = 2,
                            Role = "User",
                            UserName = "visitante1"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "user01@vinhos.pt",
                            MustChangePassword = false,
                            Password = "User01!",
                            QuintaId = 1,
                            Role = "User",
                            UserName = "user01"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 10, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "convid@vinhos.pt",
                            MustChangePassword = false,
                            Password = "Conv123!",
                            QuintaId = 5,
                            Role = "User",
                            UserName = "convidado"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 9, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "guest2@vinhos.pt",
                            MustChangePassword = true,
                            Password = "G2pass!",
                            QuintaId = 6,
                            Role = "User",
                            UserName = "guest2"
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.LogsCopos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHoraVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantidadeVendida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LogsCopos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comprador = "Cliente X",
                            DataHoraVenda = new DateTime(2025, 7, 11, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 12
                        },
                        new
                        {
                            Id = 2,
                            DataHoraVenda = new DateTime(2025, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 8
                        },
                        new
                        {
                            Id = 3,
                            Comprador = "Cliente Y",
                            DataHoraVenda = new DateTime(2025, 7, 10, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 25
                        },
                        new
                        {
                            Id = 4,
                            Comprador = "Cliente Z",
                            DataHoraVenda = new DateTime(2025, 7, 9, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 5
                        },
                        new
                        {
                            Id = 5,
                            Comprador = "Cliente W",
                            DataHoraVenda = new DateTime(2025, 7, 9, 19, 20, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 18
                        },
                        new
                        {
                            Id = 6,
                            Comprador = "Sem Venda",
                            DataHoraVenda = new DateTime(2025, 7, 8, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 0
                        },
                        new
                        {
                            Id = 7,
                            DataHoraVenda = new DateTime(2025, 7, 7, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 50
                        },
                        new
                        {
                            Id = 8,
                            Comprador = "Cliente K",
                            DataHoraVenda = new DateTime(2025, 7, 6, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 7
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.PedidoVinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdVinho")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdVinho");

                    b.ToTable("PedidoVinhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdPedido = 1,
                            IdVinho = 1,
                            Quantidade = 5
                        },
                        new
                        {
                            Id = 2,
                            IdPedido = 1,
                            IdVinho = 3,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 3,
                            IdPedido = 1,
                            IdVinho = 5,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 4,
                            IdPedido = 1,
                            IdVinho = 12,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 5,
                            IdPedido = 2,
                            IdVinho = 2,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 6,
                            IdPedido = 2,
                            IdVinho = 4,
                            Quantidade = 4
                        },
                        new
                        {
                            Id = 7,
                            IdPedido = 3,
                            IdVinho = 11,
                            Quantidade = 20
                        },
                        new
                        {
                            Id = 8,
                            IdPedido = 4,
                            IdVinho = 1,
                            Quantidade = 3
                        },
                        new
                        {
                            Id = 9,
                            IdPedido = 4,
                            IdVinho = 6,
                            Quantidade = 6
                        },
                        new
                        {
                            Id = 10,
                            IdPedido = 4,
                            IdVinho = 9,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 11,
                            IdPedido = 5,
                            IdVinho = 7,
                            Quantidade = 8
                        },
                        new
                        {
                            Id = 12,
                            IdPedido = 5,
                            IdVinho = 8,
                            Quantidade = 8
                        },
                        new
                        {
                            Id = 13,
                            IdPedido = 6,
                            IdVinho = 10,
                            Quantidade = 5
                        },
                        new
                        {
                            Id = 14,
                            IdPedido = 6,
                            IdVinho = 3,
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 15,
                            IdPedido = 6,
                            IdVinho = 12,
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 16,
                            IdPedido = 6,
                            IdVinho = 5,
                            Quantidade = 3
                        },
                        new
                        {
                            Id = 17,
                            IdPedido = 8,
                            IdVinho = 1,
                            Quantidade = 3
                        },
                        new
                        {
                            Id = 18,
                            IdPedido = 8,
                            IdVinho = 1,
                            Quantidade = 2
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Pedidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataPedido = new DateTime(2025, 7, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 2,
                            DataPedido = new DateTime(2025, 7, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 3,
                            DataPedido = new DateTime(2025, 7, 9, 16, 45, 0, 0, DateTimeKind.Utc),
                            Estado = 2
                        },
                        new
                        {
                            Id = 4,
                            DataPedido = new DateTime(2025, 7, 9, 9, 15, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 5,
                            DataPedido = new DateTime(2025, 7, 8, 11, 5, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 6,
                            DataPedido = new DateTime(2025, 7, 8, 18, 20, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 7,
                            DataPedido = new DateTime(2025, 7, 7, 19, 30, 0, 0, DateTimeKind.Utc),
                            Estado = 2
                        },
                        new
                        {
                            Id = 8,
                            DataPedido = new DateTime(2025, 7, 7, 13, 40, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Quintas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumeroMaxVinhoFrio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Quintas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Quinta Modelo",
                            NumeroMaxVinhoFrio = 20
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Quinta Vazia",
                            NumeroMaxVinhoFrio = 0
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Quinta dos Sonhos",
                            NumeroMaxVinhoFrio = 50
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Vinhedo Real",
                            NumeroMaxVinhoFrio = 30
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Encostas do Douro",
                            NumeroMaxVinhoFrio = 40
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Vale do Champagne",
                            NumeroMaxVinhoFrio = 60
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IdQuinta")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeFria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdQuinta");

                    b.ToTable("Vinhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Tinto Teste",
                            Quantidade = 50,
                            QuantidadeFria = 10
                        },
                        new
                        {
                            Id = 2,
                            Estado = 1,
                            IdQuinta = 1,
                            Nome = "Branco Oculto",
                            Quantidade = 30,
                            QuantidadeFria = 0
                        },
                        new
                        {
                            Id = 3,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Rosé Primavera",
                            Quantidade = 100,
                            QuantidadeFria = 60
                        },
                        new
                        {
                            Id = 4,
                            Estado = 0,
                            IdQuinta = 4,
                            Nome = "Espumante Real",
                            Quantidade = 80,
                            QuantidadeFria = 80
                        },
                        new
                        {
                            Id = 5,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Loureiro Verde",
                            Quantidade = 120,
                            QuantidadeFria = 70
                        },
                        new
                        {
                            Id = 6,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Alvarinho Clássico",
                            Quantidade = 60,
                            QuantidadeFria = 30
                        },
                        new
                        {
                            Id = 7,
                            Estado = 0,
                            IdQuinta = 2,
                            Nome = "Tinto Intenso",
                            Quantidade = 40,
                            QuantidadeFria = 20
                        },
                        new
                        {
                            Id = 8,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Branco Cítrico",
                            Quantidade = 25,
                            QuantidadeFria = 25
                        },
                        new
                        {
                            Id = 9,
                            Estado = 1,
                            IdQuinta = 6,
                            Nome = "Vinho de Mesa",
                            Quantidade = 200,
                            QuantidadeFria = 0
                        },
                        new
                        {
                            Id = 10,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Tinto Reserva",
                            Quantidade = 75,
                            QuantidadeFria = 15
                        },
                        new
                        {
                            Id = 11,
                            Estado = 0,
                            IdQuinta = 4,
                            Nome = "Branco Seco",
                            Quantidade = 90,
                            QuantidadeFria = 45
                        },
                        new
                        {
                            Id = 12,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Vinha Velha",
                            Quantidade = 30,
                            QuantidadeFria = 5
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Entities.UserAccount", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Quintas", "Quinta")
                        .WithMany("UserAccounts")
                        .HasForeignKey("QuintaId");

                    b.Navigation("Quinta");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.PedidoVinho", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Pedidos", "Pedido")
                        .WithMany("PedidoVinhos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppVinhosFinal.Models.Vinhos", "Vinho")
                        .WithMany("PedidoVinhos")
                        .HasForeignKey("IdVinho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Vinho");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Quintas", "Quinta")
                        .WithMany("Vinhos")
                        .HasForeignKey("IdQuinta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quinta");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Pedidos", b =>
                {
                    b.Navigation("PedidoVinhos");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Quintas", b =>
                {
                    b.Navigation("UserAccounts");

                    b.Navigation("Vinhos");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.Navigation("PedidoVinhos");
                });
#pragma warning restore 612, 618
        }
    }
}
