// <auto-generated />
using System;
using AppVinhosFinal.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppVinhosFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppVinhosFinal.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuintaId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("QuintaId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "15275553-15f4-44eb-a292-cb623faa36a2",
                            CreatedAt = new DateTime(2025, 7, 11, 7, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = false,
                            NormalizedEmail = "ADMIN@VINHOS.PT",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEK+Qb7TMU4hjo5E8s8VnJEKEnkHViHcN8h/ei9H5XsYFc4vQv9q2VpfjPembKjR0Vw==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "a929fc2f-39a3-4dc4-a486-bf6e7173f599",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "119987aa-d51e-4059-943e-95fa9e68742b",
                            CreatedAt = new DateTime(2025, 7, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff01@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = false,
                            NormalizedEmail = "STAFF01@VINHOS.PT",
                            NormalizedUserName = "STAFF01",
                            PasswordHash = "AQAAAAIAAYagAAAAEAnM9CgGU3teRP2gxoZg0KuMMduD4l5LiRoSbBppnmAMrQvkbbQ8NiokOGTLQzRtZw==",
                            PhoneNumberConfirmed = false,
                            Role = "Staff",
                            SecurityStamp = "ad692589-1309-4578-a8d0-d5a8325c48bb",
                            TwoFactorEnabled = false,
                            UserName = "staff01"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9e1e31e8-ded1-4eb2-8ff0-d202e0ca1109",
                            CreatedAt = new DateTime(2025, 7, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "visit1@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = true,
                            NormalizedEmail = "VISIT1@VINHOS.PT",
                            NormalizedUserName = "VISITANTE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEI2FIcefiyRDoI1eoTfW9sUasKVMa1qe7+yKiXbnsiUSsPJl2awXhiTvV6ZdUY8EqQ==",
                            PhoneNumberConfirmed = false,
                            QuintaId = 2,
                            Role = "User",
                            SecurityStamp = "4d36d13a-fcd9-4f82-b790-7fdc622019a2",
                            TwoFactorEnabled = false,
                            UserName = "visitante1"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "234785bd-b4bf-4384-b20e-be4700396434",
                            CreatedAt = new DateTime(2025, 7, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            Email = "user01@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = false,
                            NormalizedEmail = "USER01@VINHOS.PT",
                            NormalizedUserName = "USER01",
                            PasswordHash = "AQAAAAIAAYagAAAAEDoE8RrA4wuU5MnRBgac/J6NIa0/KVcWS8X2pjkUXr8AMh29rlaVztfuSktpJUTK1g==",
                            PhoneNumberConfirmed = false,
                            QuintaId = 1,
                            Role = "User",
                            SecurityStamp = "80bbd74b-7771-425e-8200-d5bc7f0d14d2",
                            TwoFactorEnabled = false,
                            UserName = "user01"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14ed4681-b09d-4bb4-a08c-88b481541bde",
                            CreatedAt = new DateTime(2025, 7, 10, 16, 45, 0, 0, DateTimeKind.Utc),
                            Email = "convid@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = false,
                            NormalizedEmail = "CONVID@VINHOS.PT",
                            NormalizedUserName = "CONVIDADO",
                            PasswordHash = "AQAAAAIAAYagAAAAEJr5vYU58pFpIfQo46/Qx+hnHySfA3oXQ6zBmO97Eg0tla0zVvYMwlndgpGxTfzFGA==",
                            PhoneNumberConfirmed = false,
                            QuintaId = 5,
                            Role = "User",
                            SecurityStamp = "9be5c624-fdb8-40fe-b314-c333f30ca091",
                            TwoFactorEnabled = false,
                            UserName = "convidado"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9089247a-8c9a-4c35-abfc-69724d0e782d",
                            CreatedAt = new DateTime(2025, 7, 9, 12, 20, 0, 0, DateTimeKind.Utc),
                            Email = "guest2@vinhos.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            MustChangePassword = true,
                            NormalizedEmail = "GUEST2@VINHOS.PT",
                            NormalizedUserName = "GUEST2",
                            PasswordHash = "AQAAAAIAAYagAAAAEEVBHIB3/xzTwGP68PJi+FpoExuR+MkWP2E1+mluP9Lw8vw/w0Z7FeZRy1qA8tmKgw==",
                            PhoneNumberConfirmed = false,
                            QuintaId = 6,
                            Role = "User",
                            SecurityStamp = "8f156928-b31f-44b8-a44b-2ed5f9d1a6de",
                            TwoFactorEnabled = false,
                            UserName = "guest2"
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.LogsCopos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprador")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataHoraVenda")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("QuantidadeVendida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LogsCopos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comprador = "Cliente X",
                            DataHoraVenda = new DateTime(2025, 7, 11, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 12
                        },
                        new
                        {
                            Id = 2,
                            DataHoraVenda = new DateTime(2025, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 8
                        },
                        new
                        {
                            Id = 3,
                            Comprador = "Cliente Y",
                            DataHoraVenda = new DateTime(2025, 7, 10, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 25
                        },
                        new
                        {
                            Id = 4,
                            Comprador = "Cliente Z",
                            DataHoraVenda = new DateTime(2025, 7, 9, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 5
                        },
                        new
                        {
                            Id = 5,
                            Comprador = "Cliente W",
                            DataHoraVenda = new DateTime(2025, 7, 9, 19, 20, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 18
                        },
                        new
                        {
                            Id = 6,
                            Comprador = "Sem Venda",
                            DataHoraVenda = new DateTime(2025, 7, 8, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 0
                        },
                        new
                        {
                            Id = 7,
                            DataHoraVenda = new DateTime(2025, 7, 7, 16, 5, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 50
                        },
                        new
                        {
                            Id = 8,
                            Comprador = "Cliente K",
                            DataHoraVenda = new DateTime(2025, 7, 6, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            QuantidadeVendida = 7
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QuintaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.PedidoVinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer");

                    b.Property<int>("IdVinho")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdVinho");

                    b.ToTable("PedidoVinhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdPedido = 1,
                            IdVinho = 1,
                            Quantidade = 5,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            IdPedido = 2,
                            IdVinho = 2,
                            Quantidade = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            IdPedido = 2,
                            IdVinho = 4,
                            Quantidade = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 4,
                            IdPedido = 3,
                            IdVinho = 9,
                            Quantidade = 10,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 5,
                            IdPedido = 4,
                            IdVinho = 10,
                            Quantidade = 15,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 6,
                            IdPedido = 4,
                            IdVinho = 12,
                            Quantidade = 5,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 7,
                            IdPedido = 6,
                            IdVinho = 13,
                            Quantidade = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 8,
                            IdPedido = 6,
                            IdVinho = 13,
                            Quantidade = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 9,
                            IdPedido = 7,
                            IdVinho = 17,
                            Quantidade = 5,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 10,
                            IdPedido = 7,
                            IdVinho = 19,
                            Quantidade = 4,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 11,
                            IdPedido = 8,
                            IdVinho = 21,
                            Quantidade = 6,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 12,
                            IdPedido = 9,
                            IdVinho = 22,
                            Quantidade = 8,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 13,
                            IdPedido = 9,
                            IdVinho = 23,
                            Quantidade = 2,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 14,
                            IdPedido = 9,
                            IdVinho = 24,
                            Quantidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 15,
                            IdPedido = 10,
                            IdVinho = 5,
                            Quantidade = 7,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 16,
                            IdPedido = 10,
                            IdVinho = 6,
                            Quantidade = 3,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 17,
                            IdPedido = 10,
                            IdVinho = 7,
                            Quantidade = 1,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 18,
                            IdPedido = 11,
                            IdVinho = 12,
                            Quantidade = 0,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 19,
                            IdPedido = 12,
                            IdVinho = 3,
                            Quantidade = 10,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 20,
                            IdPedido = 12,
                            IdVinho = 1,
                            Quantidade = 2,
                            Tipo = 0
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Pedidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataPedido = new DateTime(2025, 7, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 2,
                            DataAprovacao = new DateTime(2025, 7, 11, 9, 35, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 3,
                            DataPedido = new DateTime(2025, 7, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            Estado = 2
                        },
                        new
                        {
                            Id = 4,
                            DataAprovacao = new DateTime(2025, 7, 11, 16, 10, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 10, 16, 5, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 5,
                            DataPedido = new DateTime(2025, 7, 10, 18, 20, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 6,
                            DataAprovacao = new DateTime(2025, 7, 10, 10, 17, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 9, 10, 15, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 7,
                            DataPedido = new DateTime(2025, 7, 9, 12, 45, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 8,
                            DataPedido = new DateTime(2025, 7, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Estado = 2
                        },
                        new
                        {
                            Id = 9,
                            DataAprovacao = new DateTime(2025, 7, 9, 16, 35, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 8, 16, 30, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        },
                        new
                        {
                            Id = 10,
                            DataPedido = new DateTime(2025, 7, 7, 11, 15, 0, 0, DateTimeKind.Utc),
                            Estado = 0
                        },
                        new
                        {
                            Id = 11,
                            DataPedido = new DateTime(2025, 7, 7, 13, 25, 0, 0, DateTimeKind.Utc),
                            Estado = 2
                        },
                        new
                        {
                            Id = 12,
                            DataAprovacao = new DateTime(2025, 7, 7, 15, 50, 0, 0, DateTimeKind.Utc),
                            DataPedido = new DateTime(2025, 7, 6, 15, 45, 0, 0, DateTimeKind.Utc),
                            Estado = 1
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Quintas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroMaxVinhoFrio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Quintas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Quinta Modelo",
                            NumeroMaxVinhoFrio = 20
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Quinta Vazia",
                            NumeroMaxVinhoFrio = 0
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Quinta dos Sonhos",
                            NumeroMaxVinhoFrio = 50
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Vinhedo Real",
                            NumeroMaxVinhoFrio = 30
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Encostas do Douro",
                            NumeroMaxVinhoFrio = 40
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Vale do Champagne",
                            NumeroMaxVinhoFrio = 60
                        });
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadeFria")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<int>("IdQuinta")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeFria")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdQuinta");

                    b.ToTable("Vinhos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Tinto Clássico",
                            Quantidade = 50,
                            QuantidadeFria = 10
                        },
                        new
                        {
                            Id = 2,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Branco Seco",
                            Quantidade = 40,
                            QuantidadeFria = 5
                        },
                        new
                        {
                            Id = 3,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Rosé Alegre",
                            Quantidade = 60,
                            QuantidadeFria = 20
                        },
                        new
                        {
                            Id = 4,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 1,
                            Nome = "Espumante Delicado",
                            Quantidade = 30,
                            QuantidadeFria = 30
                        },
                        new
                        {
                            Id = 5,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 2,
                            Nome = "Tinto Intenso II",
                            Quantidade = 45,
                            QuantidadeFria = 0
                        },
                        new
                        {
                            Id = 6,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 2,
                            Nome = "Branco Floral",
                            Quantidade = 25,
                            QuantidadeFria = 25
                        },
                        new
                        {
                            Id = 7,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 2,
                            Nome = "Rosé de Verão",
                            Quantidade = 70,
                            QuantidadeFria = 35
                        },
                        new
                        {
                            Id = 8,
                            CapacidadeFria = 0,
                            Estado = 1,
                            IdQuinta = 2,
                            Nome = "Espumante Brut",
                            Quantidade = 80,
                            QuantidadeFria = 50
                        },
                        new
                        {
                            Id = 9,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Tinto Reserva",
                            Quantidade = 75,
                            QuantidadeFria = 15
                        },
                        new
                        {
                            Id = 10,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Branco Suave",
                            Quantidade = 90,
                            QuantidadeFria = 45
                        },
                        new
                        {
                            Id = 11,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Rosé Primavera",
                            Quantidade = 100,
                            QuantidadeFria = 60
                        },
                        new
                        {
                            Id = 12,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 3,
                            Nome = "Espumante Rosé",
                            Quantidade = 50,
                            QuantidadeFria = 50
                        },
                        new
                        {
                            Id = 13,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 4,
                            Nome = "Tinto Envelhecido",
                            Quantidade = 40,
                            QuantidadeFria = 20
                        },
                        new
                        {
                            Id = 14,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 4,
                            Nome = "Branco Cítrico",
                            Quantidade = 60,
                            QuantidadeFria = 30
                        },
                        new
                        {
                            Id = 15,
                            CapacidadeFria = 0,
                            Estado = 1,
                            IdQuinta = 4,
                            Nome = "Rosé Aromático",
                            Quantidade = 55,
                            QuantidadeFria = 25
                        },
                        new
                        {
                            Id = 16,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 4,
                            Nome = "Espumante Premium",
                            Quantidade = 80,
                            QuantidadeFria = 80
                        },
                        new
                        {
                            Id = 17,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Tinto Ensolarado",
                            Quantidade = 65,
                            QuantidadeFria = 35
                        },
                        new
                        {
                            Id = 18,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Branco Seco Especial",
                            Quantidade = 110,
                            QuantidadeFria = 70
                        },
                        new
                        {
                            Id = 19,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Rosé Tropical",
                            Quantidade = 85,
                            QuantidadeFria = 45
                        },
                        new
                        {
                            Id = 20,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 5,
                            Nome = "Espumante de Honra",
                            Quantidade = 90,
                            QuantidadeFria = 60
                        },
                        new
                        {
                            Id = 21,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Tinto Forte",
                            Quantidade = 80,
                            QuantidadeFria = 40
                        },
                        new
                        {
                            Id = 22,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Branco Frutado",
                            Quantidade = 95,
                            QuantidadeFria = 50
                        },
                        new
                        {
                            Id = 23,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Rosé Encantado",
                            Quantidade = 120,
                            QuantidadeFria = 60
                        },
                        new
                        {
                            Id = 24,
                            CapacidadeFria = 0,
                            Estado = 0,
                            IdQuinta = 6,
                            Nome = "Espumante Real",
                            Quantidade = 100,
                            QuantidadeFria = 80
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppVinhosFinal.Entities.UserAccount", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Quintas", "Quinta")
                        .WithMany("UserAccounts")
                        .HasForeignKey("QuintaId");

                    b.Navigation("Quinta");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.PedidoVinho", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Pedidos", "Pedido")
                        .WithMany("PedidoVinhos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppVinhosFinal.Models.Vinhos", "Vinho")
                        .WithMany("PedidoVinhos")
                        .HasForeignKey("IdVinho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Vinho");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.HasOne("AppVinhosFinal.Models.Quintas", "Quinta")
                        .WithMany("Vinhos")
                        .HasForeignKey("IdQuinta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quinta");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AppVinhosFinal.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AppVinhosFinal.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppVinhosFinal.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AppVinhosFinal.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Pedidos", b =>
                {
                    b.Navigation("PedidoVinhos");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Quintas", b =>
                {
                    b.Navigation("UserAccounts");

                    b.Navigation("Vinhos");
                });

            modelBuilder.Entity("AppVinhosFinal.Models.Vinhos", b =>
                {
                    b.Navigation("PedidoVinhos");
                });
#pragma warning restore 612, 618
        }
    }
}
