name: Build e Release Executável

on:
  push:
    # dispara em tags do tipo v1.2.3
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Fazer checkout
        uses: actions/checkout@v3

      - name: Instalar .NET 8.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore ./AppVinhosFinal/AppVinhosFinal.csproj

      - name: Publicar executável
        run: dotnet publish ./AppVinhosFinal/AppVinhosFinal.csproj -c Release -r win-x64 --self-contained /p:PublishSingleFile=true -o ./publish

      - name: Criar Release no GitHub
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Anexar executável à Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: publish/AppVinhosFinal.exe
          asset_name: AppVinhosFinal-${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream
